export const abonoSelect = {
  idAbono: true,
  idPedido: true,
  monto: true,
  metodoPago: true,
  referencia: true,
  fechaPago: true,
  comprobanteUrl: true,
  nombreOriginalComprobante: true,
  comprobanteMimeType: true,
  comprobanteFormato: true,
  comprobanteResourceType: true,
  comprobanteSizeBytes: true,
  comprobanteSubidoEn: true,
  montoDetectadoOcr: true,
  referenciaDetectadaOcr: true,
  fechaDetectadaOcr: true,
  bancoDetectadoOcr: true,
  confianzaOcr: true,
  requiereRevisionManual: true,
  origenRegistro: true,
  observaciones: true,
  corregidoPorId: true,
  fechaCorreccion: true,
  estado: true,
  fechaCreacion: true,
  confirmadoPorId: true,
  fechaConfirmacion: true,
  rechazadoPorId: true,
  fechaRechazo: true,
  motivoRechazo: true,
  pedido: {
    select: {
      idPedido: true,
      total: true,
      totalPagado: true,
      saldoPendiente: true,
      estadoPedido: true,
      estadoPago: true,
      cliente: {
        select: {
          idCliente: true,
          nombre: true,
          documento: true,
          correo: true,
          telefono: true,
          direccion: true,
        },
      },
    },
  },
  confirmadoPor: {
    select: {
      idUsuario: true,
      nombre: true,
      correo: true,
      rol: {
        select: {
          idRol: true,
          nombre: true,
        },
      },
    },
  },
  rechazadoPor: {
    select: {
      idUsuario: true,
      nombre: true,
      correo: true,
      rol: {
        select: {
          idRol: true,
          nombre: true,
        },
      },
    },
  },
  corregidoPor: {
    select: {
      idUsuario: true,
      nombre: true,
      correo: true,
    },
  },
} as const;
