export const cotizacionSelect = {
  idCotizacion: true,
  idCliente: true,
  creadoPorId: true,
  tipoCotizacion: true,
  estado: true,
  subtotal: true,
  descuentoTotal: true,
  costosAdicionales: true,
  total: true,
  precioSugeridoInterno: true,
  requiereRevisionPrecio: true,
  advertenciasInternas: true,
  observacionesInternas: true,
  observaciones: true,
  fechaCreacion: true,
  fechaActualizacion: true,
  cliente: {
    select: {
      idCliente: true,
      nombre: true,
      documento: true,
      telefono: true,
      correo: true,
      direccion: true,
    },
  },
  creadoPor: {
    select: {
      idUsuario: true,
      nombre: true,
      correo: true,
      rol: { select: { idRol: true, nombre: true } },
    },
  },
  detalles: {
    select: {
      idDetalleCotizacion: true,
      idTecnica: true,
      idProducto: true,
      idRangoDescuentoAplicado: true,
      tipoProducto: true,
      nombrePersonalizado: true,
      descripcionPersonalizada: true,
      materialReferencia: true,
      suministradoPor: true,
      descripcion: true,
      cantidad: true,
      precioBase: true,
      descuentoPorcentaje: true,
      cantidadMinimaDescuentoSnapshot: true,
      descuentoValorUnitario: true,
      precioUnitario: true,
      costoDiseno: true,
      subtotal: true,
      subtotalBruto: true,
      descuentoTotal: true,
      subtotalConDescuento: true,
      precioSugeridoInterno: true,
      subtotalSugeridoInterno: true,
      requiereRevisionPrecio: true,
      imagenReferencia: true,
      requiereDiseno: true,
      origenDiseno: true,
      archivoDisenoInicialUrl: true,
      esDisenoGeneral: true,
      medioRecepcionDiseno: true,
      observaciones: true,
      tecnica: {
        select: {
          idTecnica: true,
          nombre: true,
          requiereMedidas: true,
        },
      },
      producto: {
        select: {
          idProducto: true,
          idCategoriaProducto: true,
          nombre: true,
          precioBase: true,
          categoriaProducto: {
            select: {
              idCategoriaProducto: true,
              nombre: true,
            },
          },
        },
      },
      rangoDescuentoAplicado: {
        select: {
          idRango: true,
          cantidadMin: true,
          descuentoPorcentaje: true,
          estado: true,
        },
      },
      estampados: {
        select: {
          idDetalleEstampadoCotizacion: true,
          idTecnica: true,
          idTarifaAplicada: true,
          ubicacion: true,
          anchoCm: true,
          altoCm: true,
          descripcion: true,
          observaciones: true,
          origenDiseno: true,
          grupoDisenoCompartido: true,
          tarifaAnchoSnapshot: true,
          tarifaAltoSnapshot: true,
          tarifaGeneralSnapshot: true,
          precioUnitarioSugerido: true,
          descuentoPorcentajeSnapshot: true,
          subtotalBrutoSugerido: true,
          descuentoTotalSugerido: true,
          subtotalSugerido: true,
          costoDisenoSugerido: true,
          requiereRevisionPrecio: true,
          estadoMedidas: true,
          motivosRevision: true,
          tecnica: {
            select: {
              idTecnica: true,
              nombre: true,
              requiereMedidas: true,
            },
          },
        },
        orderBy: {
          idDetalleEstampadoCotizacion: "asc" as const,
        },
      },
    },
  },
  versiones: {
    select: {
      idVersion: true,
      numeroVersion: true,
      precioSugeridoInterno: true,
      precioFinal: true,
      descuentoManual: true,
      costosAdicionales: true,
      subtotalDesglose: true,
      ajusteManual: true,
      motivoAjusteManual: true,
      conceptosAdicionales: true,
      disenosOficiales: true,
      desgloseVisible: true,
      snapshotCompleto: true,
      observacionesCliente: true,
      observacionesInternas: true,
      mensajeCliente: true,
      validaHasta: true,
      enviadaAt: true,
      estado: true,
      esVigente: true,
      fechaCreacion: true,
      respuesta: {
        select: {
          idRespuesta: true,
          decision: true,
          actor: true,
          idUsuarioInterno: true,
          idCliente: true,
          medio: true,
          fechaRespuesta: true,
          observaciones: true,
          evidenciaUrl: true,
          precioAceptado: true,
          usuarioInterno: {
            select: {
              idUsuario: true,
              nombre: true,
            },
          },
        },
      },
    },
    orderBy: {
      numeroVersion: "desc" as const,
    },
  },
};

export const cotizacionListadoSelect = {
  ...cotizacionSelect,
  versiones: {
    select: {
      idVersion: true,
      numeroVersion: true,
      precioFinal: true,
      descuentoManual: true,
      costosAdicionales: true,
      subtotalDesglose: true,
      ajusteManual: true,
      observacionesCliente: true,
      mensajeCliente: true,
      validaHasta: true,
      enviadaAt: true,
      estado: true,
      esVigente: true,
      fechaCreacion: true,
      respuesta: {
        select: {
          decision: true,
          actor: true,
          medio: true,
          fechaRespuesta: true,
        },
      },
    },
    orderBy: {
      numeroVersion: "desc" as const,
    },
  },
};
