export const cotizacionSelect = {
  idCotizacion: true,
  idCliente: true,
  creadoPorId: true,
  tipoCotizacion: true,
  estado: true,
  subtotal: true,
  costosAdicionales: true,
  total: true,
  observaciones: true,
  fechaCreacion: true,
  fechaActualizacion: true,
  cliente: {
    select: {
      idCliente: true,
      nombre: true,
      documento: true,
      telefono: true,
      correo: true,
      direccion: true,
    },
  },
  creadoPor: {
    select: {
      idUsuario: true,
      nombre: true,
      correo: true,
      rol: { select: { idRol: true, nombre: true } },
    },
  },
  detalles: {
    select: {
      idDetalleCotizacion: true,
      idTecnica: true,
      idProducto: true,
      descripcion: true,
      cantidad: true,
      precioBase: true,
      descuentoPorcentaje: true,
      precioUnitario: true,
      costoDiseno: true,
      subtotal: true,
      imagenReferencia: true,
      observaciones: true,
      tecnica: { select: { idTecnica: true, nombre: true } },
      producto: {
        select: {
          idProducto: true,
          nombre: true,
          precioBase: true,
        },
      },
    },
  },
};
