export const pedidoSelect = {
  idPedido: true,
  idCotizacion: true,
  idCotizacionVersion: true,
  idCliente: true,
  estadoPedido: true,
  estadoPago: true,
  total: true,
  totalPagado: true,
  saldoPendiente: true,
  fechaCreacion: true,
  fechaEntregaEstimada: true,
  fechaFinalizado: true,
  fechaEntregado: true,
  observaciones: true,
  cliente: {
    select: {
      idCliente: true,
      nombre: true,
      documento: true,
      telefono: true,
      correo: true,
      direccion: true,
    },
  },
  cotizacion: {
    select: {
      idCotizacion: true,
      estado: true,
      subtotal: true,
      descuentoTotal: true,
      costosAdicionales: true,
      total: true,
      observaciones: true,
      creadoPor: {
        select: {
          idUsuario: true,
          nombre: true,
          correo: true,
          rol: { select: { idRol: true, nombre: true } },
        },
      },
      detalles: {
        select: {
          idDetalleCotizacion: true,
          idTecnica: true,
          idProducto: true,
          descripcion: true,
          cantidad: true,
          precioBase: true,
          descuentoPorcentaje: true,
          descuentoValorUnitario: true,
          precioUnitario: true,
          costoDiseno: true,
          subtotal: true,
          subtotalBruto: true,
          descuentoTotal: true,
          subtotalConDescuento: true,
          observaciones: true,
          tecnica: {
            select: {
              idTecnica: true,
              nombre: true,
            },
          },
          producto: {
            select: {
              idProducto: true,
              nombre: true,
              categoriaProducto: {
                select: {
                  idCategoriaProducto: true,
                  nombre: true,
                },
              },
            },
          },
        },
      },
    },
  },
  cotizacionVersion: {
    select: {
      idVersion: true,
      numeroVersion: true,
      precioFinal: true,
      descuentoManual: true,
      costosAdicionales: true,
      desgloseVisible: true,
      validaHasta: true,
      estado: true,
    },
  },
  detalles: {
    select: {
      idDetallePedido: true,
      idTecnica: true,
      idProducto: true,
      tipoProducto: true,
      nombrePersonalizado: true,
      materialReferencia: true,
      suministradoPor: true,
      descripcion: true,
      cantidad: true,
      precioUnitario: true,
      subtotal: true,
      costoDiseno: true,
      requiereDiseno: true,
      origenDiseno: true,
      archivoDisenoInicialUrl: true,
      esDisenoGeneral: true,
      medioRecepcionDiseno: true,
      observaciones: true,
      tecnica: { select: { idTecnica: true, nombre: true } },
      producto: {
        select: {
          idProducto: true,
          idCategoriaProducto: true,
          nombre: true,
          precioBase: true,
          categoriaProducto: {
            select: {
              idCategoriaProducto: true,
              nombre: true,
            },
          },
        },
      },
      estampados: {
        select: {
          idDetalleEstampadoPedido: true,
          idTecnica: true,
          ubicacion: true,
          anchoCm: true,
          altoCm: true,
          descripcion: true,
          observaciones: true,
          origenDiseno: true,
          grupoDisenoCompartido: true,
          precioUnitario: true,
          descuentoPorcentaje: true,
          subtotalBruto: true,
          descuentoTotal: true,
          subtotal: true,
          tecnica: {
            select: {
              idTecnica: true,
              nombre: true,
            },
          },
        },
        orderBy: {
          idDetalleEstampadoPedido: "asc",
        },
      },
    },
  },
  abonos: {
    select: {
      idAbono: true,
      idPedido: true,
      monto: true,
      metodoPago: true,
      referencia: true,
      comprobanteUrl: true,
      estado: true,
      fechaCreacion: true,
      confirmadoPorId: true,
      fechaConfirmacion: true,
      rechazadoPorId: true,
      fechaRechazo: true,
      motivoRechazo: true,
      nombreOriginalComprobante: true,
      comprobanteMimeType: true,
      comprobanteSizeBytes: true,
      comprobanteSubidoEn: true,
      montoDetectadoOcr: true,
      referenciaDetectadaOcr: true,
      fechaDetectadaOcr: true,
      bancoDetectadoOcr: true,
      confianzaOcr: true,
      requiereRevisionManual: true,
      origenRegistro: true,
      observaciones: true,
      confirmadoPor: {
        select: {
          idUsuario: true,
          nombre: true,
          correo: true,
          rol: { select: { idRol: true, nombre: true } },
        },
      },
      rechazadoPor: {
        select: {
          idUsuario: true,
          nombre: true,
          correo: true,
          rol: { select: { idRol: true, nombre: true } },
        },
      },
    },
    orderBy: {
      fechaCreacion: "desc",
    },
  },
  disenos: {
    select: {
      idDiseno: true,
      idPedido: true,
      idDetallePedido: true,
      idDetalleEstampadoPedido: true,
      grupoDisenoCompartido: true,
      esDisenoGeneral: true,
      idDisenador: true,
      archivoUrl: true,
      descripcion: true,
      observaciones: true,
      estado: true,
      origenDiseno: true,
      medioRecepcion: true,
      observacionesCliente: true,
      fechaRecepcion: true,
      fechaCreacion: true,
      fechaActualizacion: true,
      fechaEnvio: true,
      fechaAprobacion: true,
      detallePedido: {
        select: {
          idDetallePedido: true,
          idProducto: true,
          idTecnica: true,
          descripcion: true,
          cantidad: true,
          costoDiseno: true,
          requiereDiseno: true,
          origenDiseno: true,
          archivoDisenoInicialUrl: true,
          esDisenoGeneral: true,
          medioRecepcionDiseno: true,
          producto: {
            select: {
              idProducto: true,
              idCategoriaProducto: true,
              nombre: true,
              categoriaProducto: {
                select: {
                  idCategoriaProducto: true,
                  nombre: true,
                },
              },
            },
          },
          tecnica: {
            select: {
              idTecnica: true,
              nombre: true,
            },
          },
        },
      },
      disenador: {
        select: {
          idUsuario: true,
          nombre: true,
          correo: true,
          rol: { select: { idRol: true, nombre: true } },
        },
      },
    },
    orderBy: {
      fechaCreacion: "desc",
    },
  },
  venta: {
    select: {
      idVenta: true,
      idPedido: true,
      idCliente: true,
      totalPedido: true,
      totalPagado: true,
      saldoPendiente: true,
      fechaPrimerPago: true,
      estado: true,
      fechaCreacion: true,
      fechaActualizacion: true,
    },
  },
  _count: {
    select: {
      abonos: true,
      disenos: true,
    },
  },
} as const;
