export const PERMISOS_SISTEMA = [
  { codigo: "permisos.ver", modulo: "permisos", accion: "ver", descripcion: "Consultar permisos disponibles" },
  { codigo: "permisos.asignar", modulo: "permisos", accion: "asignar", descripcion: "Asignar permisos a roles" },
  { codigo: "roles.ver", modulo: "roles", accion: "ver", descripcion: "Consultar roles" },
  { codigo: "roles.crear", modulo: "roles", accion: "crear", descripcion: "Crear roles" },
  { codigo: "roles.editar", modulo: "roles", accion: "editar", descripcion: "Editar roles" },
  { codigo: "roles.desactivar", modulo: "roles", accion: "desactivar", descripcion: "Desactivar roles" },
  { codigo: "roles.eliminar", modulo: "roles", accion: "eliminar", descripcion: "Eliminar roles" },
  { codigo: "usuarios.ver", modulo: "usuarios", accion: "ver", descripcion: "Consultar usuarios" },
  { codigo: "usuarios.crear", modulo: "usuarios", accion: "crear", descripcion: "Crear usuarios" },
  { codigo: "usuarios.editar", modulo: "usuarios", accion: "editar", descripcion: "Editar usuarios" },
  { codigo: "usuarios.desactivar", modulo: "usuarios", accion: "desactivar", descripcion: "Desactivar usuarios" },
  { codigo: "usuarios.eliminar", modulo: "usuarios", accion: "eliminar", descripcion: "Eliminar usuarios" },
  { codigo: "clientes.ver", modulo: "clientes", accion: "ver", descripcion: "Consultar clientes externos" },
  { codigo: "clientes.desactivar", modulo: "clientes", accion: "desactivar", descripcion: "Desactivar clientes externos" },
  { codigo: "clientes.eliminar", modulo: "clientes", accion: "eliminar", descripcion: "Eliminar clientes externos sin relaciones" },
  { codigo: "tecnicas.ver", modulo: "tecnicas", accion: "ver", descripcion: "Consultar tecnicas" },
  { codigo: "tecnicas.crear", modulo: "tecnicas", accion: "crear", descripcion: "Crear tecnicas" },
  { codigo: "tecnicas.editar", modulo: "tecnicas", accion: "editar", descripcion: "Editar tecnicas" },
  { codigo: "tecnicas.desactivar", modulo: "tecnicas", accion: "desactivar", descripcion: "Desactivar tecnicas" },
  { codigo: "tecnicas.eliminar", modulo: "tecnicas", accion: "eliminar", descripcion: "Eliminar tecnicas" },
  { codigo: "cotizaciones.ver", modulo: "cotizaciones", accion: "ver", descripcion: "Consultar cotizaciones" },
  { codigo: "cotizaciones.crear_cliente", modulo: "cotizaciones", accion: "crear_cliente", descripcion: "Crear solicitud de cotizacion como cliente" },
  { codigo: "cotizaciones.editar_cliente", modulo: "cotizaciones", accion: "editar_cliente", descripcion: "Editar solicitud de cotizacion como cliente" },
  { codigo: "cotizaciones.crear_presencial", modulo: "cotizaciones", accion: "crear_presencial", descripcion: "Crear cotizacion presencial" },
  { codigo: "cotizaciones.cotizar", modulo: "cotizaciones", accion: "cotizar", descripcion: "Asignar precios a cotizaciones" },
  { codigo: "cotizaciones.editar", modulo: "cotizaciones", accion: "editar", descripcion: "Editar cotizaciones" },
  { codigo: "cotizaciones.aprobar", modulo: "cotizaciones", accion: "aprobar", descripcion: "Aprobar cotizaciones" },
  { codigo: "cotizaciones.anular", modulo: "cotizaciones", accion: "anular", descripcion: "Anular cotizaciones" },
  { codigo: "cotizaciones.eliminar", modulo: "cotizaciones", accion: "eliminar", descripcion: "Eliminar cotizaciones" },
  { codigo: "pedidos.ver", modulo: "pedidos", accion: "ver", descripcion: "Consultar pedidos" },
  { codigo: "pedidos.crear", modulo: "pedidos", accion: "crear", descripcion: "Crear pedidos" },
  { codigo: "pedidos.editar", modulo: "pedidos", accion: "editar", descripcion: "Editar pedidos" },
  { codigo: "pedidos.pasar_proceso", modulo: "pedidos", accion: "pasar_proceso", descripcion: "Pasar pedidos a produccion" },
  { codigo: "pedidos.finalizar", modulo: "pedidos", accion: "finalizar", descripcion: "Finalizar pedidos" },
  { codigo: "pedidos.anular", modulo: "pedidos", accion: "anular", descripcion: "Anular pedidos" },
  { codigo: "abonos.ver", modulo: "abonos", accion: "ver", descripcion: "Consultar abonos" },
  { codigo: "abonos.crear", modulo: "abonos", accion: "crear", descripcion: "Crear abonos" },
  { codigo: "abonos.editar", modulo: "abonos", accion: "editar", descripcion: "Editar abonos" },
  { codigo: "abonos.confirmar", modulo: "abonos", accion: "confirmar", descripcion: "Confirmar abonos" },
  { codigo: "abonos.rechazar", modulo: "abonos", accion: "rechazar", descripcion: "Rechazar abonos" },
  { codigo: "abonos.eliminar", modulo: "abonos", accion: "eliminar", descripcion: "Eliminar abonos" },
  { codigo: "disenos.ver", modulo: "disenos", accion: "ver", descripcion: "Consultar disenos" },
  { codigo: "disenos.crear", modulo: "disenos", accion: "crear", descripcion: "Crear disenos" },
  { codigo: "disenos.editar", modulo: "disenos", accion: "editar", descripcion: "Editar disenos" },
  { codigo: "disenos.aprobar", modulo: "disenos", accion: "aprobar", descripcion: "Aprobar disenos" },
  { codigo: "disenos.aprobar_cliente", modulo: "disenos", accion: "aprobar_cliente", descripcion: "Registrar aprobacion de diseno por cliente" },
  { codigo: "disenos.rechazar_cliente", modulo: "disenos", accion: "rechazar_cliente", descripcion: "Registrar rechazo de diseno por cliente" },
  { codigo: "disenos.eliminar", modulo: "disenos", accion: "eliminar", descripcion: "Eliminar disenos" },
  { codigo: "disenos.produccion", modulo: "disenos", accion: "produccion", descripcion: "Consultar produccion pendiente" },
  { codigo: "proveedores.ver", modulo: "proveedores", accion: "ver", descripcion: "Consultar proveedores" },
  { codigo: "proveedores.crear", modulo: "proveedores", accion: "crear", descripcion: "Crear proveedores" },
  { codigo: "proveedores.editar", modulo: "proveedores", accion: "editar", descripcion: "Editar proveedores" },
  { codigo: "proveedores.desactivar", modulo: "proveedores", accion: "desactivar", descripcion: "Desactivar proveedores" },
  { codigo: "proveedores.eliminar", modulo: "proveedores", accion: "eliminar", descripcion: "Eliminar proveedores" },
  { codigo: "productos.ver", modulo: "productos", accion: "ver", descripcion: "Consultar productos cotizables" },
  { codigo: "productos.crear", modulo: "productos", accion: "crear", descripcion: "Crear productos cotizables" },
  { codigo: "productos.editar", modulo: "productos", accion: "editar", descripcion: "Editar productos cotizables" },
  { codigo: "productos.desactivar", modulo: "productos", accion: "desactivar", descripcion: "Desactivar productos cotizables" },
  { codigo: "productos.eliminar", modulo: "productos", accion: "eliminar", descripcion: "Eliminar productos cotizables" },
  { codigo: "productos.precios", modulo: "productos", accion: "precios", descripcion: "Gestionar precios por cantidad de productos cotizables" },
  { codigo: "categorias_producto.ver", modulo: "categorias_producto", accion: "ver", descripcion: "Consultar categorias de productos cotizables" },
  { codigo: "categorias_producto.crear", modulo: "categorias_producto", accion: "crear", descripcion: "Crear categorias de productos cotizables" },
  { codigo: "categorias_producto.editar", modulo: "categorias_producto", accion: "editar", descripcion: "Editar categorias de productos cotizables" },
  { codigo: "categorias_producto.desactivar", modulo: "categorias_producto", accion: "desactivar", descripcion: "Desactivar categorias de productos cotizables" },
  { codigo: "categorias_producto.eliminar", modulo: "categorias_producto", accion: "eliminar", descripcion: "Eliminar categorias de productos cotizables" },
  { codigo: "compras.ver", modulo: "compras", accion: "ver", descripcion: "Consultar compras" },
  { codigo: "compras.crear", modulo: "compras", accion: "crear", descripcion: "Crear compras" },
  { codigo: "compras.editar", modulo: "compras", accion: "editar", descripcion: "Editar compras" },
  { codigo: "compras.confirmar", modulo: "compras", accion: "confirmar", descripcion: "Confirmar compras" },
  { codigo: "compras.anular", modulo: "compras", accion: "anular", descripcion: "Anular compras" },
  { codigo: "compras.eliminar", modulo: "compras", accion: "eliminar", descripcion: "Eliminar compras" },
  { codigo: "compras.resumen", modulo: "compras", accion: "resumen", descripcion: "Consultar resumen de compras" },
  { codigo: "ventas.ver", modulo: "ventas", accion: "ver", descripcion: "Consultar ventas" },
  { codigo: "ventas.resumen", modulo: "ventas", accion: "resumen", descripcion: "Consultar resumen de ventas" },
  { codigo: "dashboard.admin", modulo: "dashboard", accion: "admin", descripcion: "Consultar dashboard administrativo" },
  { codigo: "dashboard.cliente", modulo: "dashboard", accion: "cliente", descripcion: "Consultar dashboard de cliente" },
  { codigo: "cotizaciones.cliente.ver", modulo: "cotizaciones", accion: "cliente_ver", descripcion: "Consultar cotizaciones propias como cliente" },
  { codigo: "pedidos.cliente.ver", modulo: "pedidos", accion: "cliente_ver", descripcion: "Consultar pedidos propios como cliente" },
  { codigo: "abonos.cliente.ver", modulo: "abonos", accion: "cliente_ver", descripcion: "Consultar abonos propios como cliente" },
  { codigo: "disenos.cliente.ver", modulo: "disenos", accion: "cliente_ver", descripcion: "Consultar disenos propios como cliente" },
  { codigo: "disenos.cliente.aprobar", modulo: "disenos", accion: "cliente_aprobar", descripcion: "Aprobar disenos propios como cliente" },
  { codigo: "disenos.cliente.rechazar", modulo: "disenos", accion: "cliente_rechazar", descripcion: "Rechazar disenos propios como cliente" },
  { codigo: "perfil.ver", modulo: "perfil", accion: "ver", descripcion: "Consultar perfil propio" },
  { codigo: "perfil.editar", modulo: "perfil", accion: "editar", descripcion: "Editar perfil propio" },
] as const;

export type CodigoPermiso = (typeof PERMISOS_SISTEMA)[number]["codigo"];

export const PERMISOS_VALIDOS = new Set<string>(
  PERMISOS_SISTEMA.map((permiso) => permiso.codigo),
);
